### ISSUE TITLE
后续还继续新增功能吗？

### ISSUE THREAD

**Issue by HHC26** [MQEnergy/go-skeleton#1]
例如做成带前端的 web脚手架、支持更多命令的框架？

**Comment by chenxi2015** [comment]
会持续更新，需要什么也可以在评论区回复

**Comment by HHC26** [comment]
> 会持续更新，需要什么也可以在评论区回复

可以考虑一下，命令行 连接数据库，根据表生成，model（https://github.com/MQEnergy/gorm-model ）和基础的CRUD代码，这样可以减少一些重复工作

**Comment by chenxi2015** [comment]
> > 会持续更新，需要什么也可以在评论区回复
> 
> 可以考虑一下，命令行 连接数据库，根据表生成，model（https://github.com/MQEnergy/gorm-model ）和基础的CRUD代码，这样可以减少一些重复工作

这个已经在项目中集成了 
1、模型和dao生成执行命令：
`go run cmd/cli/main.go genModel -h` 

2、controller 和 service生成执行命令：
`go run cmd/cli/main.go genController -h`
`go run cmd/cli/main.go genService -h`


具体可以参考readme.md文档中有详细使用说明
