### ISSUE TITLE
使用swag init 显示找不到ctx

### ISSUE THREAD

**Issue by Zhang1506900502** [MQEnergy/go-skeleton#3]

**Comment by chenxi2015** [comment]
在根目录执行：swag init -d cmd/app -o docs 可以解决。 你可以更新下代码 执行 make swagger 命令生成docs文件

**Comment by Zhang1506900502** [comment]
好的，感谢您

**Comment by Zhang1506900502** [comment]
为什么执行这个命令始终无法检索backend中的注释生成API文档

**Comment by chenxi2015** [comment]
查看swagger文档生成：https://github.com/MQEnergy/go-skeleton/commit/6293d38e2098982200596e50ba836e06f7dc21eb
