### ISSUE TITLE
make 构建好像不支持指令增加环境

### ISSUE THREAD

**Issue by Zhang1506900502** [MQEnergy/go-skeleton#4]
make linux 打包默认是代码内的环境dev，好像不能在指令后加环境

**Comment by chenxi2015** [comment]
make linux 打包会把所有环境的config.yaml文件都打包进可执行文件  
执行 ./skeleton -h 可查看传递的参数
-e 参数是环境变量  
根据你的需要启动不同的环境 如：-e=prod  -e=test 等

**Comment by Zhang1506900502** [comment]
好滴！谢谢
